# Generated by Django 5.0 on 2023-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_bookname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookname',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
