# Generated by Django 4.2.7 on 2023-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pro', '0002_collagedata_file_field_collagedata_file_path_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collagedata',
            name='file_field',
            field=models.FileField(default='hello', upload_to='app_pro/upload/'),
        ),
        migrations.AlterField(
            model_name='collagedata',
            name='file_path_field',
            field=models.FilePathField(default='hello', path='app_pro/upload/'),
        ),
    ]
