# Generated by Django 4.2.7 on 2023-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_categorymodel_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='Task_Assign_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
