# Generated by Django 4.2.7 on 2023-12-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
